name: CI

on: ["push","pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: get tools
      run: pip install --user cpp-coveralls
      
    - name: build 
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
      
    - name: test
      run: cd build && ctest
        
    - name: code coverage
      run: |
        cd build
        coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"
