name: CI

on: ["push","pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build 
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
      
    - name: test
      run: cd build && ctest
        
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1
